version : '3'
services:
  kelompok6:
    build: ./php
    image: kelompok6_php:latest
    container_name: kelompok6
    hostname: "kelompok6"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - db_kelompok6
  db_kelompok6:
    image: mariadb:10.2
    container_name: db_kelompok6
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: pemweb_kelompok6
      MYSQL_PASSWORD: kelompok6!.
      MYSQL_ROOT_PASSWORD: kelompok6
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql  
  nginx_kelompok6:
    build: ./nginx
    image: nginx_kelompok6:latest
    container_name: nginx_kelompok6
    hostname: "nginx_kelompok6"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - kelompok6